export default [
  {
    prop: 'collapse',
    desc: '菜单是否折叠',
    type: 'Boolean',
    enum: 'true / false',
    default: 'false',
    config: true,
  },
  {
    prop: 'theme',
    desc: '皮肤类型',
    type: 'String',
    enum: 'white / dark',
    default: 'dark',
    config: true,
  },
  {
    prop: 'data',
    desc: '页面导航菜单配置文件',
    type: 'Array',
    enum: '-',
    default: '[]',
  },
  {
    prop: 'value / v-mode',
    desc: '当前激活菜单 path',
    type: 'String',
    enum: '-',
    default: '-',
  },
  {
    prop: 'router',
    desc: '是否启用 vue-router 模式',
    type: 'Boolean',
    enum: 'true / false',
    default: 'false',
  },
  {
    prop: 'otherHeight',
    desc: '排除高度，默认占高100%，如父容器有其他元素可通过这个属性设定',
    type: 'String',
    enum: '-',
    default: '-',
  },
];